create table author (
	author_id INT,
	author_name VARCHAR(50),
	birth_year INT,
	nationality VARCHAR(50)
);
insert into author (author_id, author_name, birth_year, nationality) values (1, 'Arabel Erskin', 1981, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (2, 'Conant MacSporran', 1951, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (3, 'Aurora Balham', 1944, 'Thailand');
insert into author (author_id, author_name, birth_year, nationality) values (4, 'Wynny O''Crevan', 1998, 'Luxembourg');
insert into author (author_id, author_name, birth_year, nationality) values (5, 'Glenda Geeves', 1954, 'Ukraine');
insert into author (author_id, author_name, birth_year, nationality) values (6, 'Penelopa Cocci', 1986, 'Paraguay');
insert into author (author_id, author_name, birth_year, nationality) values (7, 'Prent Obell', 1977, 'Mongolia');
insert into author (author_id, author_name, birth_year, nationality) values (8, 'Flemming Scoggin', 1975, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (9, 'Robinetta Chiddy', 1973, 'South Africa');
insert into author (author_id, author_name, birth_year, nationality) values (10, 'Melamie Loins', 1944, 'Mongolia');
insert into author (author_id, author_name, birth_year, nationality) values (11, 'Dorree Schwandermann', 1951, 'Trinidad and Tobago');
insert into author (author_id, author_name, birth_year, nationality) values (12, 'Thomasa Musgrave', 1953, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (13, 'Megan Baumer', 1969, 'Benin');
insert into author (author_id, author_name, birth_year, nationality) values (14, 'Karoly De Mattei', 1950, 'France');
insert into author (author_id, author_name, birth_year, nationality) values (15, 'Katie O''Cridigan', 1949, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (16, 'Nicolas Pranger', 1951, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (17, 'Hendrik Blackly', 1981, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (18, 'Harper Acres', 1944, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (19, 'Elfrida Hastwell', 1970, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (20, 'Maura Iggalden', 1994, 'South Africa');
insert into author (author_id, author_name, birth_year, nationality) values (21, 'Patton Keating', 1958, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (22, 'Mira Gowman', 1988, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (23, 'Heloise Maddinon', 1970, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (24, 'Milo Kohnen', 1957, 'Iran');
insert into author (author_id, author_name, birth_year, nationality) values (25, 'Angie Muldoon', 1987, 'Argentina');
insert into author (author_id, author_name, birth_year, nationality) values (26, 'Rahal Shuker', 1957, 'Yemen');
insert into author (author_id, author_name, birth_year, nationality) values (27, 'Donelle Boscott', 1975, 'Bangladesh');
insert into author (author_id, author_name, birth_year, nationality) values (28, 'Luella Beattie', 1976, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (29, 'Sully Gorioli', 1980, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (30, 'Barny Stoffer', 1976, 'Mexico');
insert into author (author_id, author_name, birth_year, nationality) values (31, 'Lishe Rablen', 1964, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (32, 'Willis Compford', 1977, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (33, 'Claiborne Litster', 1966, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (34, 'Vale Meah', 1972, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (35, 'Violetta Parnall', 1956, 'Costa Rica');
insert into author (author_id, author_name, birth_year, nationality) values (36, 'Maxy Dennis', 1967, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (37, 'Randi Greedy', 1978, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (38, 'Dud Beszant', 1981, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (39, 'Phylis Podd', 1960, 'Bulgaria');
insert into author (author_id, author_name, birth_year, nationality) values (40, 'Boigie Beagan', 1984, 'Japan');
insert into author (author_id, author_name, birth_year, nationality) values (41, 'Lorene Mouan', 1980, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (42, 'Vail Reignolds', 1999, 'Mongolia');
insert into author (author_id, author_name, birth_year, nationality) values (43, 'Hobie Mattingley', 1987, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (44, 'Terrel Dogg', 1979, 'Palestinian Territory');
insert into author (author_id, author_name, birth_year, nationality) values (45, 'Virgie Cyson', 1959, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (46, 'Alejandrina Ferrara', 1964, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (47, 'Jess Barrow', 1959, 'Saudi Arabia');
insert into author (author_id, author_name, birth_year, nationality) values (48, 'Nicolina Ragsdale', 1960, 'Chile');
insert into author (author_id, author_name, birth_year, nationality) values (49, 'Guss Mayor', 1963, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (50, 'Kyle Knappen', 1998, 'Egypt');
insert into author (author_id, author_name, birth_year, nationality) values (51, 'Joellyn Stithe', 1973, 'Czech Republic');
insert into author (author_id, author_name, birth_year, nationality) values (52, 'Tye McNeilley', 1990, 'Czech Republic');
insert into author (author_id, author_name, birth_year, nationality) values (53, 'Kissie Yallowley', 1946, 'Kosovo');
insert into author (author_id, author_name, birth_year, nationality) values (54, 'Sarena Rangeley', 1968, 'Canada');
insert into author (author_id, author_name, birth_year, nationality) values (55, 'Erminie Arnolds', 1956, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (56, 'Morna Planke', 1948, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (57, 'Arley Dockerty', 1967, 'Cuba');
insert into author (author_id, author_name, birth_year, nationality) values (58, 'Jaime Zanassi', 1946, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (59, 'Doroteya Sterling', 1968, 'Sweden');
insert into author (author_id, author_name, birth_year, nationality) values (60, 'Osborne Szabo', 1984, 'Cameroon');
insert into author (author_id, author_name, birth_year, nationality) values (61, 'Alasteir Boxell', 1962, 'Argentina');
insert into author (author_id, author_name, birth_year, nationality) values (62, 'Halsey Blaby', 1962, 'Croatia');
insert into author (author_id, author_name, birth_year, nationality) values (63, 'Barnaby Shillaker', 1946, 'Serbia');
insert into author (author_id, author_name, birth_year, nationality) values (64, 'Kaila Monro', 1963, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (65, 'Sibby Huckerbe', 1984, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (66, 'Jacenta Pinnington', 1980, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (67, 'Hermine Gansbuhler', 1960, 'South Africa');
insert into author (author_id, author_name, birth_year, nationality) values (68, 'Darcie Fayers', 1962, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (69, 'Lon Offield', 1960, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (70, 'Leoline Wegner', 1952, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (71, 'Gonzalo Stroulger', 1962, 'Faroe Islands');
insert into author (author_id, author_name, birth_year, nationality) values (72, 'Nanny Frays', 1968, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (73, 'Marika Fylan', 1988, 'Honduras');
insert into author (author_id, author_name, birth_year, nationality) values (74, 'Kelley Reeman', 2000, 'Bulgaria');
insert into author (author_id, author_name, birth_year, nationality) values (75, 'Karlene Fontanet', 1967, 'Iran');
insert into author (author_id, author_name, birth_year, nationality) values (76, 'Leora Nutter', 1994, 'France');
insert into author (author_id, author_name, birth_year, nationality) values (77, 'Gil Gligoraci', 1992, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (78, 'Sybila Cregg', 1983, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (79, 'Darn McQuilkin', 1984, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (80, 'Beverley Farncombe', 1953, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (81, 'Isiahi Selvester', 1971, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (82, 'Garvy Willarton', 1968, 'Japan');
insert into author (author_id, author_name, birth_year, nationality) values (83, 'Kimmy Hune', 1995, 'France');
insert into author (author_id, author_name, birth_year, nationality) values (84, 'Nahum Saleway', 1992, 'Lithuania');
insert into author (author_id, author_name, birth_year, nationality) values (85, 'Dionne Kaaskooper', 1983, 'South Africa');
insert into author (author_id, author_name, birth_year, nationality) values (86, 'Evaleen Josilowski', 1984, 'Bangladesh');
insert into author (author_id, author_name, birth_year, nationality) values (87, 'Derrick Hubery', 1990, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (88, 'Juli Klaiser', 1950, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (89, 'Tamas Musk', 1996, 'Mexico');
insert into author (author_id, author_name, birth_year, nationality) values (90, 'Filippo Sandal', 1972, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (91, 'Brooke Carver', 1999, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (92, 'Web Haighton', 1952, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (93, 'Benni Sorel', 1998, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (94, 'Abby Arnoldi', 1972, 'Ukraine');
insert into author (author_id, author_name, birth_year, nationality) values (95, 'Jobina Burnhams', 1960, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (96, 'Gerardo Capeling', 1985, 'Cape Verde');
insert into author (author_id, author_name, birth_year, nationality) values (97, 'Humfrey Vankin', 1975, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (98, 'Viviene Brevetor', 1967, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (99, 'Yorker Sciacovelli', 1999, 'Bangladesh');
insert into author (author_id, author_name, birth_year, nationality) values (100, 'Clementina Garbutt', 1991, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (101, 'Jeane Wandless', 1952, 'Sweden');
insert into author (author_id, author_name, birth_year, nationality) values (102, 'Brooke Fulford', 1979, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (103, 'Jo-anne Pollie', 1992, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (104, 'Gun Bruntje', 1974, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (105, 'Rafaela Ward', 1991, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (106, 'Anatol Peetermann', 1946, 'Japan');
insert into author (author_id, author_name, birth_year, nationality) values (107, 'Alberto Pancast', 1964, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (108, 'Danit Hanna', 1954, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (109, 'Dreddy Wharrier', 1965, 'Mongolia');
insert into author (author_id, author_name, birth_year, nationality) values (110, 'Kordula Fontaine', 1975, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (111, 'Husain Deehan', 1959, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (112, 'Fransisco Roswarne', 1973, 'Colombia');
insert into author (author_id, author_name, birth_year, nationality) values (113, 'Jeniffer Tolliday', 1990, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (114, 'Marty Maggiori', 1945, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (115, 'Perri McKeeman', 2000, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (116, 'Tedi Arnow', 1992, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (117, 'Rupert Dosedale', 1956, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (118, 'Roxie Teese', 1976, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (119, 'Jaine Knowler', 1953, 'Morocco');
insert into author (author_id, author_name, birth_year, nationality) values (120, 'Sherlock Trays', 1969, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (121, 'Lexy Novotna', 1945, 'Greece');
insert into author (author_id, author_name, birth_year, nationality) values (122, 'Dolorita Huard', 1971, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (123, 'Veronica Umpleby', 1951, 'Barbados');
insert into author (author_id, author_name, birth_year, nationality) values (124, 'Shari Danielsson', 1951, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (125, 'Brigitte Manssuer', 1974, 'India');
insert into author (author_id, author_name, birth_year, nationality) values (126, 'Allix Ottewill', 2000, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (127, 'Murdock Sange', 1971, 'Japan');
insert into author (author_id, author_name, birth_year, nationality) values (128, 'Gerik Parsisson', 1992, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (129, 'Stanfield Barrabeale', 1946, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (130, 'Freeman Adan', 1997, 'France');
insert into author (author_id, author_name, birth_year, nationality) values (131, 'Cobbie Guillon', 1959, 'Canada');
insert into author (author_id, author_name, birth_year, nationality) values (132, 'Netty Shrubshall', 1977, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (133, 'Brunhilde Piperley', 1983, 'Namibia');
insert into author (author_id, author_name, birth_year, nationality) values (134, 'Cordelie Rossborough', 1996, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (135, 'Tadeas Grzeszczyk', 1945, 'Jordan');
insert into author (author_id, author_name, birth_year, nationality) values (136, 'Arte Arnholdt', 1965, 'Mexico');
insert into author (author_id, author_name, birth_year, nationality) values (137, 'Novelia Phizacklea', 1975, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (138, 'Lanna Whissell', 1986, 'Croatia');
insert into author (author_id, author_name, birth_year, nationality) values (139, 'Hector Lindberg', 1973, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (140, 'Lonnard Sleite', 1977, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (141, 'Corty Benedyktowicz', 1994, 'Greece');
insert into author (author_id, author_name, birth_year, nationality) values (142, 'Mead McLenaghan', 1979, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (143, 'Stafani Huckerbe', 1958, 'South Africa');
insert into author (author_id, author_name, birth_year, nationality) values (144, 'Web McCumesky', 1982, 'Norway');
insert into author (author_id, author_name, birth_year, nationality) values (145, 'Gale Le Bosse', 1986, 'Nigeria');
insert into author (author_id, author_name, birth_year, nationality) values (146, 'Tan Gaskoin', 1949, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (147, 'Joey Gillam', 1956, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (148, 'Margit Tollfree', 1986, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (149, 'Jan McKeowon', 1981, 'Thailand');
insert into author (author_id, author_name, birth_year, nationality) values (150, 'Corabella Van den Oord', 1967, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (151, 'Ham Nodin', 1948, 'South Africa');
insert into author (author_id, author_name, birth_year, nationality) values (152, 'Anissa Tarren', 1994, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (153, 'Bogart Deluce', 2000, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (154, 'Marlon Reach', 1995, 'Netherlands');
insert into author (author_id, author_name, birth_year, nationality) values (155, 'Gibbie Le Noire', 1996, 'Thailand');
insert into author (author_id, author_name, birth_year, nationality) values (156, 'Jarrad Mallatratt', 1979, 'Cuba');
insert into author (author_id, author_name, birth_year, nationality) values (157, 'Koralle Philbin', 1997, 'Sweden');
insert into author (author_id, author_name, birth_year, nationality) values (158, 'Chelsie Olivazzi', 1955, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (159, 'Stefanie Tibbits', 1963, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (160, 'Rahel Bullcock', 1971, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (161, 'Brooks Daily', 2000, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (162, 'Lani Coggin', 1969, 'Bangladesh');
insert into author (author_id, author_name, birth_year, nationality) values (163, 'Garwin Kinset', 1999, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (164, 'Silva Sherland', 1962, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (165, 'Mersey Hebard', 1993, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (166, 'Kristian O''Cullen', 1983, 'Ireland');
insert into author (author_id, author_name, birth_year, nationality) values (167, 'Milton Mabone', 1963, 'Greece');
insert into author (author_id, author_name, birth_year, nationality) values (168, 'Austin Coultass', 1967, 'Sweden');
insert into author (author_id, author_name, birth_year, nationality) values (169, 'Shara Sclater', 1972, 'Macedonia');
insert into author (author_id, author_name, birth_year, nationality) values (170, 'Alika Braley', 1996, 'Egypt');
insert into author (author_id, author_name, birth_year, nationality) values (171, 'Malina Kinrade', 1963, 'Kenya');
insert into author (author_id, author_name, birth_year, nationality) values (172, 'Misti Paul', 1947, 'Myanmar');
insert into author (author_id, author_name, birth_year, nationality) values (173, 'Byran Ledster', 1993, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (174, 'Dame Fivey', 1955, 'Azerbaijan');
insert into author (author_id, author_name, birth_year, nationality) values (175, 'Zia Malone', 1944, 'Central African Republic');
insert into author (author_id, author_name, birth_year, nationality) values (176, 'Adda Shafto', 1950, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (177, 'Meredeth Licciardello', 1945, 'Uganda');
insert into author (author_id, author_name, birth_year, nationality) values (178, 'Ethelyn Birdwhistle', 1977, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (179, 'Ilyssa Whear', 1945, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (180, 'Deck Rolph', 1965, 'Liberia');
insert into author (author_id, author_name, birth_year, nationality) values (181, 'Stanfield Muir', 1963, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (182, 'Angelique Folonin', 1978, 'North Korea');
insert into author (author_id, author_name, birth_year, nationality) values (183, 'Dari Scardifeild', 1963, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (184, 'Maxwell Galsworthy', 1964, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (185, 'La verne Bahlmann', 1993, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (186, 'Ebony Debow', 1956, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (187, 'Irena Grimbaldeston', 1961, 'Sweden');
insert into author (author_id, author_name, birth_year, nationality) values (188, 'Bartlet Gwatkin', 1967, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (189, 'Lorinda Luckie', 1944, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (190, 'Willie Dekeyser', 1976, 'Iran');
insert into author (author_id, author_name, birth_year, nationality) values (191, 'Sibyl Inge', 1952, 'Peru');
insert into author (author_id, author_name, birth_year, nationality) values (192, 'Caresa Bidder', 1979, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (193, 'Corine O'' Cuolahan', 1963, 'Mexico');
insert into author (author_id, author_name, birth_year, nationality) values (194, 'Maurizio Kopta', 1958, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (195, 'Anallise Keatch', 1974, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (196, 'Cherye Lages', 1971, 'Malaysia');
insert into author (author_id, author_name, birth_year, nationality) values (197, 'Mae Digges', 1975, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (198, 'Ronna Donhardt', 1977, 'Iran');
insert into author (author_id, author_name, birth_year, nationality) values (199, 'Maxy Egalton', 1958, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (200, 'Mercedes Kyndred', 1973, 'Honduras');
insert into author (author_id, author_name, birth_year, nationality) values (201, 'Tamma Turpin', 1991, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (202, 'Elwyn Caldecourt', 1987, 'Canada');
insert into author (author_id, author_name, birth_year, nationality) values (203, 'Pennie Winsom', 1970, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (204, 'Ximenez Yole', 1982, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (205, 'Edeline Chaudrelle', 1976, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (206, 'Gipsy Cross', 1967, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (207, 'Rodie Gouch', 1963, 'Senegal');
insert into author (author_id, author_name, birth_year, nationality) values (208, 'Carlyle Force', 1945, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (209, 'Christa Rowes', 1957, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (210, 'Dasya Bagster', 1974, 'Norway');
insert into author (author_id, author_name, birth_year, nationality) values (211, 'Gloriane Faughnan', 1950, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (212, 'Sal Guerra', 1973, 'France');
insert into author (author_id, author_name, birth_year, nationality) values (213, 'Stanton Rowbotham', 1989, 'Uzbekistan');
insert into author (author_id, author_name, birth_year, nationality) values (214, 'Chery Richardson', 1997, 'Vietnam');
insert into author (author_id, author_name, birth_year, nationality) values (215, 'Brendon Stickels', 1995, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (216, 'Tootsie Duckit', 1990, 'France');
insert into author (author_id, author_name, birth_year, nationality) values (217, 'Lona Rakestraw', 1958, 'Kazakhstan');
insert into author (author_id, author_name, birth_year, nationality) values (218, 'Jonis Diack', 1944, 'Mexico');
insert into author (author_id, author_name, birth_year, nationality) values (219, 'Charmane Nary', 1998, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (220, 'Abe Charrier', 1998, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (221, 'Filide Ginni', 1963, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (222, 'Marilyn Cathery', 1992, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (223, 'Tandi Treversh', 1996, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (224, 'George Danielli', 1983, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (225, 'Drake Chafney', 1944, 'Belarus');
insert into author (author_id, author_name, birth_year, nationality) values (226, 'Virgil Tinan', 1974, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (227, 'Willette Pembridge', 1967, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (228, 'Tim Gobert', 1964, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (229, 'Babita Ellaway', 1975, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (230, 'Nettie Thornton', 1974, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (231, 'Rubi Burberow', 1973, 'Guinea');
insert into author (author_id, author_name, birth_year, nationality) values (232, 'Roberto Fawckner', 1966, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (233, 'Kathlin Willden', 1998, 'South Sudan');
insert into author (author_id, author_name, birth_year, nationality) values (234, 'Kenna Milsom', 1994, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (235, 'Korella Kahn', 1988, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (236, 'Gabriel Clewett', 1989, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (237, 'George Trengove', 1973, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (238, 'Corbet Flatman', 1955, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (239, 'Keefe Leatherborrow', 1962, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (240, 'Roarke Beswell', 1988, 'Colombia');
insert into author (author_id, author_name, birth_year, nationality) values (241, 'Chrysa Cockarill', 1956, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (242, 'Morgen McAlinden', 1989, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (243, 'Andrey Sylett', 1968, 'Mexico');
insert into author (author_id, author_name, birth_year, nationality) values (244, 'Aurel Beldham', 1983, 'Greece');
insert into author (author_id, author_name, birth_year, nationality) values (245, 'Gideon Jaggers', 2000, 'Japan');
insert into author (author_id, author_name, birth_year, nationality) values (246, 'Anabal Langlais', 1963, 'Thailand');
insert into author (author_id, author_name, birth_year, nationality) values (247, 'Dorene Handley', 1963, 'Tanzania');
insert into author (author_id, author_name, birth_year, nationality) values (248, 'Robby Clawsley', 1958, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (249, 'Ferrell Leggat', 1995, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (250, 'Edlin Martill', 1956, 'South Korea');
insert into author (author_id, author_name, birth_year, nationality) values (251, 'Marje Marskell', 1979, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (252, 'Fernando Reddy', 1989, 'Sweden');
insert into author (author_id, author_name, birth_year, nationality) values (253, 'Hyacinth Litt', 1994, 'United States');
insert into author (author_id, author_name, birth_year, nationality) values (254, 'Paulina Duberry', 1995, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (255, 'Libbie Plessing', 1965, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (256, 'Agatha Coll', 1949, 'Peru');
insert into author (author_id, author_name, birth_year, nationality) values (257, 'Hillery Taphouse', 1967, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (258, 'Wrennie Tillman', 1965, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (259, 'Karlan Wynes', 1946, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (260, 'Min Leon', 1994, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (261, 'Esther Bedboro', 1995, 'Morocco');
insert into author (author_id, author_name, birth_year, nationality) values (262, 'Bentlee Farlane', 1962, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (263, 'Verile Skase', 1973, 'France');
insert into author (author_id, author_name, birth_year, nationality) values (264, 'Orella Corkill', 1958, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (265, 'Torrence Bothwell', 1973, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (266, 'Adah Jameson', 1959, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (267, 'Baldwin Edney', 1968, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (268, 'Cahra Pickton', 1959, 'Nigeria');
insert into author (author_id, author_name, birth_year, nationality) values (269, 'Olivette Devenport', 1978, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (270, 'Glynis Wolfenden', 1997, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (271, 'Valera Elsbury', 1979, 'Israel');
insert into author (author_id, author_name, birth_year, nationality) values (272, 'Lizzy Devany', 1983, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (273, 'Ambros Stokes', 1969, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (274, 'Jordan Kohtler', 1986, 'Croatia');
insert into author (author_id, author_name, birth_year, nationality) values (275, 'Krystyna Sture', 1994, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (276, 'Davis Goude', 1970, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (277, 'Giacinta Badam', 1993, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (278, 'Flss Aizikovitz', 1989, 'Chile');
insert into author (author_id, author_name, birth_year, nationality) values (279, 'Francesco Leborgne', 1969, 'Poland');
insert into author (author_id, author_name, birth_year, nationality) values (280, 'Paddie Wedderburn', 1963, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (281, 'Daisi Tarr', 1998, 'Brazil');
insert into author (author_id, author_name, birth_year, nationality) values (282, 'Tad Meekin', 1946, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (283, 'Donnajean Crame', 1998, 'Tanzania');
insert into author (author_id, author_name, birth_year, nationality) values (284, 'Ody Orsi', 1947, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (285, 'Lefty Panyer', 1957, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (286, 'Sylvester Gellan', 1966, 'China');
insert into author (author_id, author_name, birth_year, nationality) values (287, 'Sam Carl', 1980, 'Germany');
insert into author (author_id, author_name, birth_year, nationality) values (288, 'Clemmie Hobden', 1973, 'Portugal');
insert into author (author_id, author_name, birth_year, nationality) values (289, 'Isabeau St Ledger', 1985, 'Canada');
insert into author (author_id, author_name, birth_year, nationality) values (290, 'Stuart Vaggers', 1950, 'Ethiopia');
insert into author (author_id, author_name, birth_year, nationality) values (291, 'Federica Curzon', 1961, 'Iran');
insert into author (author_id, author_name, birth_year, nationality) values (292, 'Nannette Restieaux', 1978, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (293, 'Tildi Wonfor', 1948, 'Sudan');
insert into author (author_id, author_name, birth_year, nationality) values (294, 'Trixy Wreakes', 1985, 'Thailand');
insert into author (author_id, author_name, birth_year, nationality) values (295, 'Othilie Akhurst', 1944, 'Ukraine');
insert into author (author_id, author_name, birth_year, nationality) values (296, 'Tanney Yanukhin', 1945, 'Indonesia');
insert into author (author_id, author_name, birth_year, nationality) values (297, 'Caresa Danovich', 1960, 'Philippines');
insert into author (author_id, author_name, birth_year, nationality) values (298, 'Hettie Sangwin', 1989, 'Sweden');
insert into author (author_id, author_name, birth_year, nationality) values (299, 'Ruben Bartolommeo', 1977, 'Russia');
insert into author (author_id, author_name, birth_year, nationality) values (300, 'Florence Duce', 1999, 'Brazil');
